In [25]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("turkish_song_lyrics.csv")

In [3]:
df

,singer,song,album,lyrics
0,Barış Manço,Abbas Yolcu,24 Ayar,Denizlerde okyanuslarda\nDalgaların koynunda b...
1,Barış Manço,Acıhda Baga Vir,2023,Acıhda bağa vir biraz da oğa vir\nÇevir kazı y...
2,Barış Manço,Adem Oğlu Kızgın Fırın Havva Kızı Mercimek,Hal Hal,Adem babayla Havva anadan bu yana \nÇok şeyler...
3,Barış Manço,Affet Beni,Sahibinden İhtiyaçtan,Beni bırakıp gittiğinden beri\nTerkedilmiş bir...
4,Barış Manço,Ah Tut,Live In Japan,"Ah tut-i mucize guyem, ne desem laf değil x2\n..."
...,...,...,...,...
4423,Şebnem Ferah,İnsanlık,Benim Adım Orman,Aynıydı gökyüzümüz\nSavrulduk her birimiz\nİns...
4424,Şebnem Ferah,İstiklal Caddesi Kadar,Benim Adım Orman,Alnımdan akan ter\nSana hiç değmedi\nGözümden ...
4425,Şebnem Ferah,İyi Gün Dostlarım,Kadın,Hangi gün hangi an üzülsem ağlasam\nHalime gül...
4426,Şebnem Ferah,İyi Kötü (Dans Pisti),Kelimeler Yetse,Biriyle fena halde konuşmaya ihtiyacım var \nB...
4427,Şebnem Ferah,Şarkılar Yalan Söylemez,Parmak İzi,Ömür kapkaranlık\nNasıl aydınlanır\nBen yanmaz...

### DataFrame düzenleme

In [4]:
df = df.loc[:,["singer", "lyrics"]]

In [5]:
df.head()

        singer                                             lyrics
0  Barış Manço  Denizlerde okyanuslarda\nDalgaların koynunda b...
1  Barış Manço  Acıhda bağa vir biraz da oğa vir\nÇevir kazı y...
2  Barış Manço  Adem babayla Havva anadan bu yana \nÇok şeyler...
3  Barış Manço  Beni bırakıp gittiğinden beri\nTerkedilmiş bir...
4  Barış Manço  Ah tut-i mucize guyem, ne desem laf değil x2\n...

In [6]:
df["No"] = df.index+1

In [7]:
df = df.set_index("No")

In [8]:
df.head()

         singer                                             lyrics
No
1   Barış Manço  Denizlerde okyanuslarda\nDalgaların koynunda b...
2   Barış Manço  Acıhda bağa vir biraz da oğa vir\nÇevir kazı y...
3   Barış Manço  Adem babayla Havva anadan bu yana \nÇok şeyler...
4   Barış Manço  Beni bırakıp gittiğinden beri\nTerkedilmiş bir...
5   Barış Manço  Ah tut-i mucize guyem, ne desem laf değil x2\n...

### cleaning

In [9]:
df.lyrics = df.lyrics.str.replace("\d","")

In [10]:
df.head()

         singer                                             lyrics
No
1   Barış Manço  Denizlerde okyanuslarda\nDalgaların koynunda b...
2   Barış Manço  Acıhda bağa vir biraz da oğa vir\nÇevir kazı y...
3   Barış Manço  Adem babayla Havva anadan bu yana \nÇok şeyler...
4   Barış Manço  Beni bırakıp gittiğinden beri\nTerkedilmiş bir...
5   Barış Manço  Ah tut-i mucize guyem, ne desem laf değil x\nB...

In [11]:
sw = stopwords.words('turkish')
ex_sw = ["sen", "böyle", "şöyle", "mi", "ben", "yine",'i', "bi", "gene",
         "nakarat", "verse", "x", "kimden", "ne", "sözmüzik", "sana",
         "ona", "bana", "oh", "oy", "ha", "bize", "size","seni","beni",
         "bir","söz", "müzik", "le"]
sw.extend(ex_sw)
print(sw)

['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani', 'sen', 'böyle', 'şöyle', 'mi', 'ben', 'yine', 'i', 'bi', 'gene', 'nakarat', 'verse', 'x', 'kimden', 'ne', 'sözmüzik', 'sana', 'ona', 'bana', 'oh', 'oy', 'ha', 'bize', 'size', 'seni', 'beni', 'bir', 'söz', 'müzik', 'le']

In [12]:
df["no_stop"] = df["lyrics"].str.lower().apply(lambda x: ' '.join([word for word in x.split() if word not in (sw)]))

In [13]:
df.head()

,singer,lyrics,no_stop
No,,,
1,Barış Manço,Denizlerde okyanuslarda\nDalgaların koynunda b...,denizlerde okyanuslarda dalgaların koynunda öm...
2,Barış Manço,Acıhda bağa vir biraz da oğa vir\nÇevir kazı y...,acıhda bağa vir biraz oğa vir çevir kazı yanma...
3,Barış Manço,Adem babayla Havva anadan bu yana \nÇok şeyler...,adem babayla havva anadan yana şeyler söylendi...
4,Barış Manço,Beni bırakıp gittiğinden beri\nTerkedilmiş bir...,bırakıp gittiğinden beri terkedilmiş çocuk çar...
5,Barış Manço,"Ah tut-i mucize guyem, ne desem laf değil x\nB...","ah tut-i mucize guyem, desem laf değil beli ya..."

In [14]:
df.no_stop[251]

'güneş akşam batıp gün doğuyorsa çiçekler solup solup tekrar açıyorsa derin yaralar kapanıyorsa büyük acılar unutuluyorsa korkulur hayatta söyleyin aynı kalayım söyleyin elbette bazen çiçek açıp bazen solacağım elbette daldan dala konup sonra uçacağım elbette bazen hızla dönüp bazen duracağım elbette bazen söyleyip bazen susacağım i̇nanmadım asla inanamam şeyin sonu olduğuna elbette bugün ağlıyorsam yarın güleceğim elbette önce çekip gidip sonra döneceğim'

### bert-sentiment

In [15]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

model = AutoModelForSequenceClassification.from_pretrained("savasy/bert-base-turkish-sentiment-cased")
tokenizer = AutoTokenizer.from_pretrained("savasy/bert-base-turkish-sentiment-cased")
sa= pipeline("sentiment-analysis", tokenizer=tokenizer, model=model)

In [16]:
list_no_stop = df.no_stop.tolist()

In [17]:
söz_score = []
for söz in range(len(list_no_stop)):
    score = sa(list_no_stop[söz], truncation=True)
    söz_score.append(score)

In [18]:
söz_score[250]

[{'label': 'positive', 'score': 0.9896217584609985}]

In [19]:
list_label = []
for i in range(len(söz_score)):
    for j in range(1):
        list_label.append(söz_score[i][j]["label"])

In [20]:
list_label[250]

'positive'

In [21]:
list_score = []
for i in range(len(söz_score)):
    for j in range(1):
        list_score.append(söz_score[i][j]["score"])

In [22]:
list_score[250]

0.9896217584609985

In [23]:
df["+/-"] = list_label

In [26]:
df["Score"] = np.array(list_score)

https://stackoverflow.com/questions/26666919/add-column-in-dataframe-from-list

In [27]:
df.head()

,singer,lyrics,no_stop,+/-,Score
No,,,,,
1,Barış Manço,Denizlerde okyanuslarda\nDalgaların koynunda b...,denizlerde okyanuslarda dalgaların koynunda öm...,negative,0.957016
2,Barış Manço,Acıhda bağa vir biraz da oğa vir\nÇevir kazı y...,acıhda bağa vir biraz oğa vir çevir kazı yanma...,negative,0.964071
3,Barış Manço,Adem babayla Havva anadan bu yana \nÇok şeyler...,adem babayla havva anadan yana şeyler söylendi...,negative,0.977146
4,Barış Manço,Beni bırakıp gittiğinden beri\nTerkedilmiş bir...,bırakıp gittiğinden beri terkedilmiş çocuk çar...,positive,0.521777
5,Barış Manço,"Ah tut-i mucize guyem, ne desem laf değil x\nB...","ah tut-i mucize guyem, desem laf değil beli ya...",negative,0.670776

In [31]:
df.no_stop[251]

'güneş akşam batıp gün doğuyorsa çiçekler solup solup tekrar açıyorsa derin yaralar kapanıyorsa büyük acılar unutuluyorsa korkulur hayatta söyleyin aynı kalayım söyleyin elbette bazen çiçek açıp bazen solacağım elbette daldan dala konup sonra uçacağım elbette bazen hızla dönüp bazen duracağım elbette bazen söyleyip bazen susacağım i̇nanmadım asla inanamam şeyin sonu olduğuna elbette bugün ağlıyorsam yarın güleceğim elbette önce çekip gidip sonra döneceğim'

In [33]:
df["+/-"][251]

'positive'

In [34]:
df.Score[251]

0.9896217584609985

In [37]:
df.to_csv("lyrics_w_scores_sw.csv", index = False)