In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [6]:
df = pd.read_csv("turkish_song_lyrics.csv")

In [7]:
df

,singer,song,album,lyrics
0,Barış Manço,Abbas Yolcu,24 Ayar,Denizlerde okyanuslarda\nDalgaların koynunda b...
1,Barış Manço,Acıhda Baga Vir,2023,Acıhda bağa vir biraz da oğa vir\nÇevir kazı y...
2,Barış Manço,Adem Oğlu Kızgın Fırın Havva Kızı Mercimek,Hal Hal,Adem babayla Havva anadan bu yana \nÇok şeyler...
3,Barış Manço,Affet Beni,Sahibinden İhtiyaçtan,Beni bırakıp gittiğinden beri\nTerkedilmiş bir...
4,Barış Manço,Ah Tut,Live In Japan,"Ah tut-i mucize guyem, ne desem laf değil x2\n..."
...,...,...,...,...
4423,Şebnem Ferah,İnsanlık,Benim Adım Orman,Aynıydı gökyüzümüz\nSavrulduk her birimiz\nİns...
4424,Şebnem Ferah,İstiklal Caddesi Kadar,Benim Adım Orman,Alnımdan akan ter\nSana hiç değmedi\nGözümden ...
4425,Şebnem Ferah,İyi Gün Dostlarım,Kadın,Hangi gün hangi an üzülsem ağlasam\nHalime gül...
4426,Şebnem Ferah,İyi Kötü (Dans Pisti),Kelimeler Yetse,Biriyle fena halde konuşmaya ihtiyacım var \nB...
4427,Şebnem Ferah,Şarkılar Yalan Söylemez,Parmak İzi,Ömür kapkaranlık\nNasıl aydınlanır\nBen yanmaz...

In [8]:
df.lyrics = df.lyrics.str.replace("\n",". ")

In [10]:
df.lyrics[30]

'Bir masaldı aşkımız sisler bulutlar ardında. Bir akşam bitiverdi her şey yokoldu bir anda. Beyhude geçti yıllar silindi hatıralar. Geride bir avuç yalan. Hüzün dolu geceler buğulu pencereler. İşte hepsi bu senden kalan. Nasıl içim yanıyor öylesine sevdim seni. Hep saklamak istedim altın kafeslerde seni. Beyhude geçti yıllar silindi hatıralar. Geride bir avuç yalan. Hüzün dolu geceler buğulu pencereler. İşte hepsi bu senden kalan Sanki gizli bir el kopardı seni benden. Savurdu bir kar tanesi gibi. Boş yere arıyorum sımsıcacık sevgini. Bu ıslak boş sokaklarda elinden oyuncağı. Alınmış çocuk gibi yalnızım sokaklarda. Bir masaldı aşkımız sisler bulutlar ardında. Bir akşam bitiverdi her şey yokoldu bir anda. Beyhude geçti yıllar silindi hatıralar. Geride bir avuç yalan. Hüzün dolu geceler buğulu pencereler. İşte hepsi bu senden kalan'

### sentence tokenization

In [13]:
from nltk import sent_tokenize

In [14]:
def tokenize_sentences(text):
    sentences = sent_tokenize(text)
    
    return sentences

In [15]:
df["sentences"] = df["lyrics"].apply(tokenize_sentences)

In [16]:
df

,singer,song,album,lyrics,sentences
0,Barış Manço,Abbas Yolcu,24 Ayar,Denizlerde okyanuslarda. Dalgaların koynunda b...,"[Denizlerde okyanuslarda., Dalgaların koynunda..."
1,Barış Manço,Acıhda Baga Vir,2023,Acıhda bağa vir biraz da oğa vir. Çevir kazı y...,"[Acıhda bağa vir biraz da oğa vir., Çevir kazı..."
2,Barış Manço,Adem Oğlu Kızgın Fırın Havva Kızı Mercimek,Hal Hal,Adem babayla Havva anadan bu yana . Çok şeyler...,"[Adem babayla Havva anadan bu yana ., Çok şeyl..."
3,Barış Manço,Affet Beni,Sahibinden İhtiyaçtan,Beni bırakıp gittiğinden beri. Terkedilmiş bir...,"[Beni bırakıp gittiğinden beri., Terkedilmiş b..."
4,Barış Manço,Ah Tut,Live In Japan,"Ah tut-i mucize guyem, ne desem laf değil x2. ...","[Ah tut-i mucize guyem, ne desem laf değil x2...."
...,...,...,...,...,...
4423,Şebnem Ferah,İnsanlık,Benim Adım Orman,Aynıydı gökyüzümüz. Savrulduk her birimiz. İns...,"[Aynıydı gökyüzümüz., Savrulduk her birimiz., ..."
4424,Şebnem Ferah,İstiklal Caddesi Kadar,Benim Adım Orman,Alnımdan akan ter. Sana hiç değmedi. Gözümden ...,"[Alnımdan akan ter., Sana hiç değmedi., Gözümd..."
4425,Şebnem Ferah,İyi Gün Dostlarım,Kadın,Hangi gün hangi an üzülsem ağlasam. Halime gül...,"[Hangi gün hangi an üzülsem ağlasam., Halime g..."
4426,Şebnem Ferah,İyi Kötü (Dans Pisti),Kelimeler Yetse,Biriyle fena halde konuşmaya ihtiyacım var . B...,"[Biriyle fena halde konuşmaya ihtiyacım var .,..."
4427,Şebnem Ferah,Şarkılar Yalan Söylemez,Parmak İzi,Ömür kapkaranlık. Nasıl aydınlanır. Ben yanmaz...,"[Ömür kapkaranlık., Nasıl aydınlanır., Ben yan..."

In [17]:
df = df.loc[:,["singer", "lyrics", "sentences"]] #satırların hepsi

In [18]:
df

,singer,lyrics,sentences
0,Barış Manço,Denizlerde okyanuslarda. Dalgaların koynunda b...,"[Denizlerde okyanuslarda., Dalgaların koynunda..."
1,Barış Manço,Acıhda bağa vir biraz da oğa vir. Çevir kazı y...,"[Acıhda bağa vir biraz da oğa vir., Çevir kazı..."
2,Barış Manço,Adem babayla Havva anadan bu yana . Çok şeyler...,"[Adem babayla Havva anadan bu yana ., Çok şeyl..."
3,Barış Manço,Beni bırakıp gittiğinden beri. Terkedilmiş bir...,"[Beni bırakıp gittiğinden beri., Terkedilmiş b..."
4,Barış Manço,"Ah tut-i mucize guyem, ne desem laf değil x2. ...","[Ah tut-i mucize guyem, ne desem laf değil x2...."
...,...,...,...
4423,Şebnem Ferah,Aynıydı gökyüzümüz. Savrulduk her birimiz. İns...,"[Aynıydı gökyüzümüz., Savrulduk her birimiz., ..."
4424,Şebnem Ferah,Alnımdan akan ter. Sana hiç değmedi. Gözümden ...,"[Alnımdan akan ter., Sana hiç değmedi., Gözümd..."
4425,Şebnem Ferah,Hangi gün hangi an üzülsem ağlasam. Halime gül...,"[Hangi gün hangi an üzülsem ağlasam., Halime g..."
4426,Şebnem Ferah,Biriyle fena halde konuşmaya ihtiyacım var . B...,"[Biriyle fena halde konuşmaya ihtiyacım var .,..."
4427,Şebnem Ferah,Ömür kapkaranlık. Nasıl aydınlanır. Ben yanmaz...,"[Ömür kapkaranlık., Nasıl aydınlanır., Ben yan..."

In [20]:
df.sentences[30]

['Bir masaldı aşkımız sisler bulutlar ardında.',
 'Bir akşam bitiverdi her şey yokoldu bir anda.',
 'Beyhude geçti yıllar silindi hatıralar.',
 'Geride bir avuç yalan.',
 'Hüzün dolu geceler buğulu pencereler.',
 'İşte hepsi bu senden kalan.',
 'Nasıl içim yanıyor öylesine sevdim seni.',
 'Hep saklamak istedim altın kafeslerde seni.',
 'Beyhude geçti yıllar silindi hatıralar.',
 'Geride bir avuç yalan.',
 'Hüzün dolu geceler buğulu pencereler.',
 'İşte hepsi bu senden kalan Sanki gizli bir el kopardı seni benden.',
 'Savurdu bir kar tanesi gibi.',
 'Boş yere arıyorum sımsıcacık sevgini.',
 'Bu ıslak boş sokaklarda elinden oyuncağı.',
 'Alınmış çocuk gibi yalnızım sokaklarda.',
 'Bir masaldı aşkımız sisler bulutlar ardında.',
 'Bir akşam bitiverdi her şey yokoldu bir anda.',
 'Beyhude geçti yıllar silindi hatıralar.',
 'Geride bir avuç yalan.',
 'Hüzün dolu geceler buğulu pencereler.',
 'İşte hepsi bu senden kalan']

### sentiment analysis

In [21]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

model = AutoModelForSequenceClassification.from_pretrained("savasy/bert-base-turkish-sentiment-cased")
tokenizer = AutoTokenizer.from_pretrained("savasy/bert-base-turkish-sentiment-cased")
sa= pipeline("sentiment-analysis", tokenizer=tokenizer, model=model)

In [31]:
sentence_list = df.sentences.tolist()

In [32]:
sentence_list

[['Denizlerde okyanuslarda.',
  'Dalgaların koynunda bir ömür tükettikten sonra.',
  'Su için boğulmak varsa.',
  'Çöllerde kızgın kumlarda karlı buzlu dağlarda.',
  'Bir ömür tükettikten sonra.',
  'Çukurda kaybolmak varsa.',
  'Korkunun ecele faydası yok.',
  'Bu koşuşma niye.',
  'Abbas yolcu soran yok.',
  'Yolculuk nereye kim kaldı geriye Taş üstüne taş koya koya.',
  'Yarattığımız dünyanın.',
  'Çöktüğünü görmek bir yana bir de altında kalmak var ya.',
  'Korkunun ecele faydası yok.',
  'Bu koşuşma niye.',
  'Abbas yolcu soran yok.',
  'Yolculuk nereye kim kaldı geriye.',
  'Sana uzatılan elleri.',
  'Görmek istemesen de.',
  'Bir gün o eller üstünde bu dünyadan göçmek var ya'],
 ['Acıhda bağa vir biraz da oğa vir.',
  'Çevir kazı yanmasın aman kız uyanmasın.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Canı kaymak isteyen cebinde manda taşır.',
  'Canı kaymak isteyen cebinde manda taşır.',
  'Bulguru yağı bulan çorbasın kaynatır.',
  'Ya bulamayan gariban omzunu oynatır.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Çevir kazı yanmasın aman kız uyanmasın.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Ayağında yok postal başına giyer püskül.',
  'Ayağında yok postal başına giyer püskül Sonradan görmesi meğersem ne müşkül.',
  'Ya hiç bir şey bilmemek pilav üstüne keşkül.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Ayrana daldır yoğurduna saldır.',
  'Selam veğdi gödün mü.',
  'Selamı ağmadın mı aa.',
  'Çevir kazı yanmasın aman kız uyanmasın.',
  'Türkünün sonu geldi gari.',
  'Haydaaa.',
  'Balcının baltası var oduncunun baltası var.',
  'Öyle de olur böyle de olur.',
  'Avcı vurur turnayı biz çalarız zurnayı.',
  'Öyle de olur böyle de olur'],
 ['Adem babayla Havva anadan bu yana .',
  'Çok şeyler söylendi sevda üzerine.',
  'Sayısız türküler yapıldı Leyla ile Mecnun Ferhat ile Şirin.',
  'Hepside dertli ayrılıklarla biten ızdırap gözyaşı dolu.',
  'Hani karabasan gibi insanın dünyasını karartan sıkıntılı şeylerdi.',
  'Bugün Barış kardeşiniz sizlere yeni bir türkü söyleyecek.',
  'Çünkü Barış gördü ki yeryüzünde en büyük gerçek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Kız dediğin nazlı olur erkek ise mangal yürek.',
  'Er kişinin yanında hatun gerek.',
  'Kız dediğin nazlı olur erkek ise mangal yürek.',
  'Er kişinin yanında hatun gerek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Kız olmazsa er kişi kolsuz kanatsız demek.',
  'Davulu dengi dengine vurmak gerek.',
  'Kız olmazsa er kişi kolsuz kanatsız demek.',
  'Davulu dengi dengine vurmak gerek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Mercimek fırın yan yana fazla söze ne gerek.',
  'Deli gönül sevdi mi istemez yorgan döşek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Kimi zeytin peynir yer kimi baklava börek.',
  'Kimine saray dar gelir kimine bir oda gerek.',
  'İki göz bir kulübe yeter Havva kızına.',
  'Adem oğlu kalender yiyeceği bir lokma ekmek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Tanrı böyle buyurmuş dünya böyle kurulmuş.',
  'Her Adem oğluna bir Havva nasip olmuş.',
  'Tanrı böyle buyurmuş dünya böyle kurulmuş.',
  'Her Adem oğluna bir Havva nasip olmuş.',
  'Yedi iklim dört kuşak inanmazsan gitte bak.',
  "Nuh'un gemisinde bile fırın mercimek dolmuş.",
  'Adem oğlu kızgın fırın Havva kızı mercimek'],
 ['Beni bırakıp gittiğinden beri.',
  'Terkedilmiş bir çocuk gibi.',
  'Çaresizim dolaştım gecelerde.',
  'Sana döndüm yine biliyorum suç bende.',
  'Affet beni ne olur affet beni.',
  'Yalvarırım soru sorma.',
  'Verilecek cevabım yok suç bende.',
  'Affet affet beni.',
  'Kendi evimde bir yabancı gibi.',
  'Çıktım ağır ağır merdivenleri.',
  'Kapıyı çalmaya cesaretim yok.',
  'Sana döndüm yine biliyorum suç bende Affet beni ne olur affet beni.',
  'Yalvarırım soru sorma.',
  'Verilecek cevabım yok suç bende.',
  'Affet affet beni.',
  'Son bir kez seni görmek istedim.',
  'Geceler boyu bu anı bekledim.',
  'Sana dönmemi istemiyorsan söyle.',
  'Söyle gideyim ama önce yine de.',
  'Affet beni ne olur affet beni.',
  'Yalvarırım soru sorma.',
  'Verilecek cevabım yok suç bende.',
  'Affet affet beni'],
 ['Ah tut-i mucize guyem, ne desem laf değil x2.',
  'Beli yarim beli dost.',
  'Beli mirim beli dost.',
  'Beli ömrüm beli dost.',
  'Ah çerh ile söyleşemem ayinesi saf değil x2.',
  'Beli yarim beli dost.',
  'Beli mirim beli dost.',
  'Beli ömrüm beli dost.',
  'Ah ehl-i dildir diyemem sinesi saf olmayana x2.',
  'Beli yarim beli dost.',
  'Beli mirim beli dost.',
  'Beli ömrüm beli dost'],
 ['Tanrı bütün kullara rızkını dağıtırken.',
  'Kimi sırtüstü yatar kimi boşta gezerken.',
  'Kul Ahmet erken kalkar haydi ya nasip derdi.',
  'Kimseler anlamazdı ya nasip ne demekti.',
  'O mahallede herkes gömlek giyerdi.',
  'Bizim kul Ahmet bir gün bir ceket diktirdi diktirir ya.',
  "Mahalleye dert oldu kul Ahmet'in ceketi .",
  'Kul Ahmet erken kalkar haydi ya nasip derdi.',
  'Kimseler anlamazdı ya nasip ne demekti.',
  'Herkes gömlek giyerken Ahmet ceket giyerdi.',
  "Konu komşuya dert oldu kul Ahmet'in ceketi.",
  'Mahalleli kahvede muhabbet peşindeyken.',
  'Leylekler lak lak edip peynir gemisi yüklerken.',
  'Kul Ahmet erken yatar sabaha ya kısmet derdi.',
  'Kimseler anlamazdı ya kısmet ne demekti.',
  'Herkes gömlek giye dursun Bizim kul Ahmet ceketini birde astarla kaplatıverdi kaplatır ya.',
  "Mahalleye dert oldu kul Ahmet'in ceketi .",
  'Kul Ahmet erken yatar sabaha ya kısmet derdi.',
  'Kimseler anlamazdı ya kısmet ne demekti.',
  'Herkes gömlek giyerdi .',
  "Konu komşuya dert oldu kul Ahmet'in ceketi .",
  'Bir gün bir yoksul öldü üzüldü mahalleli.',
  'Ama bir kefen parası bulamadı mahalleli .',
  'Kul Ahmet dedi yalan dünya çıkardı ceketini.',
  'Örttü garibin üstüne kaldırdı cenazeyi.',
  'Sonunda herkes anladı ya nasip ya kısmeti.',
  'Bizim kul Ahmet birdenbire oluverdi Ahmet bey.',
  'Ceket ise Ahmet beyin ceketi.',
  'İbreti alem oldu Ahmet beyin ceketi.',
  'Sonunda herkes anladı ya nasip ya kısmeti.',
  'İbreti alem oldu Ahmet beyin ceketi.',
  'Meğerse tüm keramet ceketteymiş be Ahmet.',
  'Barış a sorar isen sen bu yolda devam et'],
 ['Sen gideli sevgilim, bahçemde güller açmıyor.',
  'Geceler bitmek bilmiyor, geceler buz gibi, sabah olmuyor.',
  'Şimdi ben sensiz nasıl yaşarım söyle.',
  'Şimdi ben sensiz neylerim söyle.',
  'Son birkez görebilsem seni, tutsam dokunsam ellerine.',
  'Yokluğun dayanılmaz oldu, hasret kaldım gül yüzüne.',
  'Şimdi ben sensiz nasıl yaşarım söyle.',
  'Şimdi ben sensiz neylerim söyle.',
  'Şimdi ben sensiz nasıl yaşarım söyle.',
  'Al beni götür gittiğin yere.',
  'İstersen vur yerden yerlere Ne olur, al beni götür gittiğin yere.',
  'Yeter ki yeter ki terketme.',
  'Bekledim seni gecelerce yaralı ceylan misali.',
  "Ardından düştüm çöllere Leyla'ya koşan Mecnun misali.",
  'Şimdi ben sensiz neylerim söyle.',
  'Şimdi ben sensiz nasıl yaşarım söyle.',
  'AL beni götür gittiğin yere.',
  'İstersen vur yerden yerlere.',
  'Ne olur al beni götür gittiğin yere.',
  'Yeter ki yeter ki terketme'],
 ['Ali yazar Veli bozar küp suyunu çeker azar azar.',
  'Gözümde yaş görseler erkek ağlar mı derler .',
  'Gökler ağlıyor dostlar ben ağlamışım çok mu.',
  'Rahmet yağarken dostlar ben ıslanmışım çok mu.',
  'Ali yazar Veli bozar küp suyunu çeker azar azar.',
  'Üzülmüşüm neye yarar keskin sirke küpüne zarar.',
  'Bir gün dönsem sözümden düşerim dost gözünden.',
  'Dünya dönüyor dostlar bir sözden dönsem çok mu.',
  'Devran dönüyor dostlar ben dönmüşüm çok mu.',
  'Ali yazar Veli bozar küp suyunu çeker azar azar.',
  'Üzülmüşüm neye yarar keskin sirke küpüne zarar.',
  'Barış yolun sonunda yürü demek boşuna.',
  'Hayat duruyor dostlar ben durmuşum çok mu.',
  'Yaşam bitiyor dostlar ben bitmişim çok mu'],
 ['Alla beni pulla beni al koynuna yar.',
  'Gözüm senden başkasını görmez oldu yar.',
  'Gönlüm senden bir şey ister nasıl desem yar.',
  'Alla beni pulla beni al koynuna yar.',
  'Senin için dağlar deler yol açarım yar.',
  'Senin için denizleri kuruturum yar.',
  'Senin için gök kubbeyi yerlere çalarım yar.',
  'Canım iste canım bile sana kurban yar.',
  'Dağlar taşlar uçan kuşlar senin olsun yar.',
  'Deniz derya gökler hep yerinde dursun yar.',
  'Gönlüm senden bir şey ister nasıl desem yar.',
  'Alla beni pulla beni al koynuna yar.',
  'Saçlarına yıldızlardan taç yapayım yar.',
  'Bir nefeste güneşleri söndüreyim yar Çıra gibi uğrunda ben yanayım yar.',
  'Canım iste canım bile sana kurban yar.',
  'Yıldızlar yerinde güzel bırak dursun yar.',
  'Saçlarımı ellerinle okşa yeter yar.',
  'Gönlüm senden bir şey ister nasıl desem yar.',
  'Alla beni pulla beni al koynuna yar.',
  'Rüzgar olup ince beline sarılayım yar.',
  'Çimen olup ayağına serileyim yar.',
  'Sürme olup gözlerine sürüleyim yar.',
  'Canım iste canım bile sana kurban yar.',
  'Alla beni pulla beni al koynuna yar.',
  'Gözüm senden başkasını görmez oldu yar.',
  'Gönlüm senden bir şey ister nasıl desem yar.',
  'Alla beni pulla beni al koynuna yar'],
 ['Yine sensiz geçen bir gecenin.',
  'Buz gibi sabahında.',
  'Bu korkunç yalnızlığımda.',
  'Seni bekliyorum yanıyor yüreğim.',
  'Yine gözyaşlarım yağmur gibi.',
  'Yaşıyorum anılarla.',
  'Birşeyler kopuyor sanki.',
  'Taa şuramda yanıyor yüreğim.',
  'Allahım güç ver bana sığındım sana.',
  'Bu ne dayanılmaz acı sabır ver bana.',
  'Yeter artık çektiklerim bitsin bu ceza.',
  'Ümitsiz haykırıyorum ne olur dön bana Sana yazdığım en son şarkı bu.',
  'Artık kırıldı kalemim.',
  'Gökler şahidim olsun ki.',
  'Seni seviyorum yanıyor yüreğim.',
  'Sonbahar yaprakları gibi.',
  'Savruldu ümitlerim.',
  'Son bir kez duymak istersen.',
  'Seni seviyorum yanıyor yüreğim.',
  'Allahım güç ver bana sığındım sana.',
  'Bu ne dayanılmaz acı sabır ver bana.',
  'Yeter artık çektiklerim bitsin bu ceza.',
  'Ümitsiz haykırıyorum ne olur dön bana'],
 ['Aman avcı vurma beni.',
  'Ben yaralı ay balam yaralıyam.',
  'Yaralıyam ben yaralı.',
  'Avcı vurmuş ay balam yaralıyam.',
  'Bir taş attım çaya düştü.',
  'Çaydan bir çift ay balam tuna uçtu.',
  'Benim gönlüm sana düştü.',
  'Senin gönlün ay balam kime düştü?.',
  'Bu dağlarda ceylan gezer.',
  'Tırnakların ay balam taşla ezer.',
  'Ben o yare neylemişem.',
  'O yar benden ay balam ırak gezer'],
 ['Aman yavaş aheste.',
  'Sabırlı derviş murada ermiş.',
  'Acelesi olana ağır ol demiş.',
  'Aman demiş aheste.',
  'Aman yavaş aheste.',
  'Tiz-i reftar olanın payine dağmen dolaşır.',
  'Erişir menzil-i maksuda aheste giden.',
  'Aheste çek kürekleri aheste.',
  'Perdedari mikoned der kasr-ı Kayzer ankebut,.',
  'Bum nevbet mizedend der târem-i Efrâsiyâb.',
  'Aman yavaş aheste.',
  'Söz gümüşse sükut altınmış.',
  'Demek ki susmak daha kıymetli.',
  'Sessiz sakin durmak varken.',
  'Konuşup yorulana bilmem ne demeli.',
  'Aman yavaş aheste'],
 ['Sabah seher vakti düştüm yola.',
  'Anam sordu nire oğlum böyle.',
  'Dedim ana fazla sorma bağrım yanık yeter sorma.',
  'Seher vakti düştüm yola.',
  'Günler boyu yol aldım durmadım.',
  'Pınar başlarında konakladım.',
  'Dağlar taşlar geçit verdi .',
  'Çayır çimen kilim serdi.',
  'Seher vakti düştüm yola.',
  'Ben bir yeşil gözlü yar sevmiştim .',
  'Gece gündüz başın beklemiştim.',
  'Bir kış günü vakit çaldı Yarim son uykuya daldı.',
  'Uyanmadı gitti uzaklara.',
  'Yıllarca kurda kuşa dert yandım.',
  'Zaman geçer unuturum sandım.',
  'Kerem derdiyle yanarmış.',
  'Mecnunsa ölüp solarmış.',
  'Benim derdim vurdu beni yola.',
  'Sorarlar Barış ne edersin orda.',
  'Nasıl ağır gelmez mi ki sıla.',
  'İşte içim döktüm sormayın artık tanrı aşkına.',
  'Benim derdim vurdu beni yola'],
 ['Sınıfın en güzel kızı o yalnız geziyor kimse ona yaklaşamıyor.',
  'Yine koltuğunda koca koca kitaplar kütüphaneden geliyor.',
  'Baktım bir cilt şair Mehmet Akif.',
  'İki büyük kitap Fatih Sultan Mehmet.',
  'Üç kalın cilt Mevlana birde Mimar Sinan.',
  'Döndü bana dediki eğer beni seviyorsan .',
  'Eğer kalbime girmek istiyorsan.',
  'Önce bunları anla beni iyi dinle.',
  'Beş şair bir abide.',
  'İki abide bir sultan.',
  'Beş sultan bir düşünür.',
  'İki düşünür ise bir mimar.',
  'Düşün taşın bütün gece.',
  'Benim kalbim bir bilmece.',
  'Kalbimin bir kilidi var.',
  'İşte sana anahtar.',
  'En sevdiği şair Mehmet Akif.',
  'Bir abide Fatih Sultan Mehmet.',
  'Hayranım dedi Sinan bir de Mevlana.',
  'Gece annem evde dedi oğlum neyin var.',
  'Yemeden içmeden kesildin yine.',
  'Dedim anne kalbimin sahibi var aşık oldum delicesine.',
  'Bir gün Akif okuyor bir gün Mevlana.',
  'Bir Fatihe Hayranmış bir de Sinana.',
  'Hem tarihe meraklıymış hem de sanata.',
  'Annem dedi oğlum anlamadım ben.',
  'Vazgeç bu sevdadan bu kız fazla akıllı Ah beim saf oğlum ah oğlum anlamadın mı.',
  'Beş şair bir abide.',
  'İki abide bir sultan.',
  'Beş sultan bir düşünür.',
  'İki düşünür ise bir mimar.',
  'Düşün taşın bütün gece.',
  'Benim kalbim bir bilmece.',
  'Kalbimin bir kilidi var.',
  'İşte sana anahtar.',
  'En sevdiği şair Mehmet Akif.',
  'Bir abide Fatih Sultan Mehmet.',
  'Hayranım dedi Sinan bir de Mevlana.',
  'Aşkın gözü kör olurmuş .',
  'Annem galiba haklı.',
  'Kafama fena takıldı bu kız çok akıllı.',
  'Beş şair bir abide.',
  'İki abide bir sultan.',
  'Beş sultan bir düşünür.',
  'İki düşünür ise bir mimar.',
  'Düşün taşın bütün gece.',
  'Benim kalbim bir bilmece.',
  'Kalbimin bir kilidi var.',
  'İşte sana anahtar.',
  'Beş Akif bir saat kulesi.',
  'İki kule bir Fatih.',
  'Beş fatih bir Mevlana.',
  'İki Mevlana bir Sinan'],
 ['Hava ayaz mı ayaz ellerim ceplerimde .',
  'Bir türkü tutturmuşum duyuyorsun değil mi?.',
  'Çalacak bir kapım yok mutluluğa hasretim .',
  'Artık sokaklar benim görüyorsun değil mi? .',
  'Zaman akmıyor sanki saatler durmuş bugün .',
  'Sonsuz yalnızlığımda bir tek sen varsın bugün .',
  'Ya dön bana artık duyuyor musun beni? .',
  'Ya çık git dünyamdan anlıyorsun değil mi? .',
  'Bir resmin kalmış bende tam ortadan yırtılmış .',
  'Hani siyah kazaklı biliyorsun değil mi? .',
  'Gözlerimden süzülen birkaç damla anıda .',
  'Senin sıcaklığın var anlıyorsun değil mi?'],
 ['Kaç yıl oldu saymadım köyden göçeli.',
  'Mevsimler geldi geçti görüşmeyeli.',
  'Hiç haber göndermedin o günden beri.',
  'Yoksa bana küstün mü unuttun mu beni.',
  'Dün yine seni andım gözlerim doldu.',
  'O tatlı günlerimiz bir anı oldu.',
  'Ayrılık geldi başa katlanmak gerek.',
  'Seni çok çok özledim arkadaşım eşek.',
  'Arkadaşım eş arkadaşım şek arkadaşım eşek Yaban tayları çayırda tepişiyor mu.',
  'Çilli horoz kedilerle dövüşüyor mu.',
  'Sarıkız minik buzağıyı sütten kesti mi.',
  'Kuzularla oğlaklar sevişiyor mu.',
  'Uzun kulaklarını son bir kez salla.',
  'Tüm eski dostlarımdan bir haber yolla.',
  'Ayrılık geldi başa katlanmak gerek.',
  'Seni çok çok özledim arkadaşım eşek .',
  'Arkadaşım eş arkadaşım şek arkadaşım eşek'],
 ['Sabahın yemişi bir tane kişmiş sabahın yemişi bir tane kişmiş.',
  'Giderim gelirem ardıma düşme ay Osman.',
  'Giderim gelirem ardıma düşme ay Osman.',
  'Yürü hayırüha geçmişem elden yürü hayırüha geçmişem elden.',
  'Ayrılık vadesi içmişim elden ay Osman.',
  'Ayrılık vadesi içmişim elden ay Osman.',
  'Sabahın yemişi bir tane kişmiş sabahın yemişi bir tane kişmiş.',
  'Uyandım nazlı yar ellere gitmiş ay Osman .',
  'Uyandım nazlı yar ellere gitmiş ay Osman .',
  'Yürü hayırüha geçmişem elden yürü hayırüha geçmişem elden Ayrılık vadesi içmişim elden ay Osman.',
  'Ayrılık vadesi içmişim elden ay Osman.',
  'Sabahın yemişi bir tane elma sabahın yemişi bir tane elma.',
  'İlahi canımı al yarimi alma ay Osman.',
  'İlahi canımı al yarimi alma ay Osman.',
  'Yürü hayırüha geçmişem elden yürü hayırüha geçmişem elden.',
  'Ayrılık vadesi içmişim elden ay Osman.',
  'Ayrılık vadesi içmişim elden ay Osman'],
 ['Sabah yeli ılgıt ılgıt eserken seher vakti bir güzele vuruldum .',
  'Al dudakta inci dişi bu dünyada yok bir eşi .',
  'Seher vakti bir güzele vuruldum .',
  'Aynalı kemer ince bele bu can kurban tatlı dile .',
  'Seher vakti bir güzele vuruldum .',
  'Mor menekşe nergiz dizmiş boynuna .',
  'Kuşluk vakti aldı beni koynuna .',
  'Cıvıldaşır dudu kuşu sanki bülbülün ötüşü .',
  'Seher vakti bir güzele vuruldum Aynalı kemer ince bele bu can kurban tatlı dile .',
  'Seher vakti bir güzele vuruldum .',
  'Akşam oldu gün kavuştu sessizce .',
  'Dedi güzel ayrılık vardı bize .',
  'Uzakta bir baykuş öttü gül bahçemde diken bitti .',
  'Seher vakti bir güzele vuruldum .',
  'Aynalı kemer ince bele bu can kurban tatlı dile .',
  'Seher vakti bir güzele vuruldum'],
 ['Fikrimden geceler yatabilmirem.',
  'Bu fikri başımdan atabilmirem.',
  'Neyleyim ki sene çatabilmirem.',
  'Ayrılık, ayrılık aman ayrılık.',
  'Herbir dertten olar yaman ayrılık.',
  'Uzundur hicrimden gara geceler.',
  'Bilmirem men gidim hara geceler.',
  'Vuruptur gelbime yara geceler.',
  'Ayrılık, ayrılık aman ayrılık.',
  'Her bir dertten olar yaman ayrılık'],
 ['Bugün hava güzel dedim ki hanıma .',
  'Haydi kalk giyin de çıkalım biraz .',
  'Bak cıvıl cıvıl kuşlar uçuyor.',
  'Dalları basmış erikle kiraz.',
  'Çoluk çocuk cümbür cemaat .',
  'Piknik yapalım ne dersiniz ha?.',
  'Ev halkı uçtu yihhu aslan baba sen çok yaşa.',
  'Yolda düşündüm bizim çocuklar tanımıyorlar hayvanları.',
  'Bir hayli garibime gitti doğrusu bir baba olarak verdim kararı.',
  'Anında bir ters U dönüş doğru hayvanat bahçesine.',
  'Biliyoruz ayıp oldu hakim bey ama zar zor girebildik içeriye.',
  'Bak evladım buna ayı derler.',
  'Ormandan inip şehre gelirler.',
  'Biraz ağırdır, hantaldır ama.',
  'Armudun iyisini ayılar yerler.',
  'Evet babacım ona ayı derler .',
  'Ayılar bizleri çok severler.',
  'Ağır mağır hantaldır ama.',
  'Armudun iyisini ayılar yerler.',
  'Seninde canın günün birinde Armudun iyisini yemek isterse.',
  'Sakın ha aman manava gidip te .',
  'Armutları tek tek elleme.',
  'Adamın kafası bir atarsa.',
  'Bayramlık ağzını bir açarsa.',
  'Sana neler der biliyor musun.',
  'Mahalle duyar rezil olursun.',
  'A de bakayım -A- bi de Y de -Y- şimdi bi de I -I-.',
  'Oku bakayım AYI oku bakayım AYI.',
  'Maksat çoluk çoçuk öğrensin hayatın çetin yollarını.',
  'Kaptırmasınlar kimseye kafalarını ve kollarını.',
  'Hani baba olarak vazifemiz tabi uyandırıp ikaz etmek.',
  'Uzunlar yanmıyor hakim bey kısa yoldan anlatmak gerek.',
  'Hayvan sevgisi tabiki lazım ama herşey karşılıklı.',
  'Ben seni seveyim sende beni say ki bozulmasın ağzımızın tadı.',
  'Armudun iyisini zaten o yer bir eli yağda ötekisi balda.',
  'Buramıza geldi artık hakim bey takdir sizden birazda ite kaka.',
  'A de bakayım -A- bi de Y de -Y- şimdi bi de I -I-.',
  'Oku bakayım AYI oku bakayım AYI'],
 ['Rüya gibi her hatıra her yaşantı bana.',
  'Rüya gibi her hatıra her yaşantı bana.',
  'Ne bulduysa kaybetti gönül aşktan yana.',
  'Ne bulduysa kaybetti gönül aşktan yana.',
  'Ömür çiçek kadar narin bir gün kadar kısa.',
  'Ağlama değmez hayat bu gözyaşlarına.',
  'Ağlama değmez hayat bu gözyaşlarına.',
  'Her damla yaş oyuk oyuk iz bırakır kalbimde.',
  'Her damla yaş oyuk oyuk iz bırakır kalbimde.',
  'Hayat şarap gibidir keder de var neşe de.',
  'Hayat şarap gibidir keder de var neşe de.',
  'Ömür çiçek kadar narin bir gün kadar kısa.',
  'Ağlama değmez hayat bu gözyaşlarına.',
  'Ağlama değmez hayat bu gözyaşlarına'],
 ['(x2).',
  'Bahçede hanımeli.',
  'Sen ettin beni deli.',
  'Gel gülüm gel.',
  'Sen ettin beni deli.',
  'Gel Gülüm Gel.',
  'Zorla güzellik olmaz.',
  'Sevmeli sevdirmeli.',
  'Gel gülüm gel.',
  'Sevmeli sevdirmeli'],
 ['Seyyah oldum dolaştım şu alemi, ah güzelim.',
  'Senin gibi bir vefasız görmedim ben.',
  'Hayırsızı, kitapsızı, zalimi, bal böceğim.',
  'Senin gibi bir insafsız görmedim ben.',
  'Şu dağlarda çiçek oldum, aşkından sarardım soldum.',
  'Bakmadın bana bal böceğim.',
  'Yollarında toprak oldum, sen bastıkça ben kavruldum.',
  'Görmedin beni bal böceğim.',
  'Seni gidi bal böceği.',
  'Kim çözecek bu bilmeceyi.',
  'Ateşte yanar pervane, ben oldum derdinden divane.',

In [ ]:
if p[0]['label']=='positive':

In [25]:
def analyze_sentiment(lyrics_sentence):
    sentiments = []
    
    for sentence in lyrics_sentence:
        sentiment = sa(sentence)
        
        sentiments.append(sentiment)
        
    return

df["sentiment"] = df["sentences"].apply(analyze_sentiment)

In [26]:
df.to_csv("lyrics_sentence_sentiment.csv", index=False)

In [27]:
df

,singer,lyrics,sentences,sentiment
0,Barış Manço,Denizlerde okyanuslarda. Dalgaların koynunda b...,"[Denizlerde okyanuslarda., Dalgaların koynunda...",None
1,Barış Manço,Acıhda bağa vir biraz da oğa vir. Çevir kazı y...,"[Acıhda bağa vir biraz da oğa vir., Çevir kazı...",None
2,Barış Manço,Adem babayla Havva anadan bu yana . Çok şeyler...,"[Adem babayla Havva anadan bu yana ., Çok şeyl...",None
3,Barış Manço,Beni bırakıp gittiğinden beri. Terkedilmiş bir...,"[Beni bırakıp gittiğinden beri., Terkedilmiş b...",None
4,Barış Manço,"Ah tut-i mucize guyem, ne desem laf değil x2. ...","[Ah tut-i mucize guyem, ne desem laf değil x2....",None
...,...,...,...,...
4423,Şebnem Ferah,Aynıydı gökyüzümüz. Savrulduk her birimiz. İns...,"[Aynıydı gökyüzümüz., Savrulduk her birimiz., ...",None
4424,Şebnem Ferah,Alnımdan akan ter. Sana hiç değmedi. Gözümden ...,"[Alnımdan akan ter., Sana hiç değmedi., Gözümd...",None
4425,Şebnem Ferah,Hangi gün hangi an üzülsem ağlasam. Halime gül...,"[Hangi gün hangi an üzülsem ağlasam., Halime g...",None
4426,Şebnem Ferah,Biriyle fena halde konuşmaya ihtiyacım var . B...,"[Biriyle fena halde konuşmaya ihtiyacım var .,...",None
4427,Şebnem Ferah,Ömür kapkaranlık. Nasıl aydınlanır. Ben yanmaz...,"[Ömür kapkaranlık., Nasıl aydınlanır., Ben yan...",None

### example

In [59]:
df_new = df.head(5)

In [60]:
df_new

,singer,lyrics,sentences,sentiment
0,Barış Manço,Denizlerde okyanuslarda. Dalgaların koynunda b...,"[Denizlerde okyanuslarda., Dalgaların koynunda...",None
1,Barış Manço,Acıhda bağa vir biraz da oğa vir. Çevir kazı y...,"[Acıhda bağa vir biraz da oğa vir., Çevir kazı...",None
2,Barış Manço,Adem babayla Havva anadan bu yana . Çok şeyler...,"[Adem babayla Havva anadan bu yana ., Çok şeyl...",None
3,Barış Manço,Beni bırakıp gittiğinden beri. Terkedilmiş bir...,"[Beni bırakıp gittiğinden beri., Terkedilmiş b...",None
4,Barış Manço,"Ah tut-i mucize guyem, ne desem laf değil x2. ...","[Ah tut-i mucize guyem, ne desem laf değil x2....",None

In [67]:
sentence_ex_list = df_new.sentences.tolist()

In [76]:
def analyze_sentiment(lyrics_sentence):
    sentiments = []
    
    for sentence in lyrics_sentence:
        sentiment = sa(sentence, truncation=True)
        
        sentiments.append(sentiment)
        
    return

#df_new["sentiment"] = df_new["sentences"].apply(analyze_sentiment)

for index, row in df_new.iterrows():
  #Tokenize the sentence
  input_ids = sa(row['sentences'])

  #Get the sentiment prediction from the model
  output = model(input_ids)
  sentiment_ex = output[0].argmax().item()

  #Add the sentiment prediction to the dataframe
  df_new.loc[index, 'sentiment_new'] = sentiment_ex

In [71]:
sentence_ex_list

[['Denizlerde okyanuslarda.',
  'Dalgaların koynunda bir ömür tükettikten sonra.',
  'Su için boğulmak varsa.',
  'Çöllerde kızgın kumlarda karlı buzlu dağlarda.',
  'Bir ömür tükettikten sonra.',
  'Çukurda kaybolmak varsa.',
  'Korkunun ecele faydası yok.',
  'Bu koşuşma niye.',
  'Abbas yolcu soran yok.',
  'Yolculuk nereye kim kaldı geriye Taş üstüne taş koya koya.',
  'Yarattığımız dünyanın.',
  'Çöktüğünü görmek bir yana bir de altında kalmak var ya.',
  'Korkunun ecele faydası yok.',
  'Bu koşuşma niye.',
  'Abbas yolcu soran yok.',
  'Yolculuk nereye kim kaldı geriye.',
  'Sana uzatılan elleri.',
  'Görmek istemesen de.',
  'Bir gün o eller üstünde bu dünyadan göçmek var ya'],
 ['Acıhda bağa vir biraz da oğa vir.',
  'Çevir kazı yanmasın aman kız uyanmasın.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Canı kaymak isteyen cebinde manda taşır.',
  'Canı kaymak isteyen cebinde manda taşır.',
  'Bulguru yağı bulan çorbasın kaynatır.',
  'Ya bulamayan gariban omzunu oynatır.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Çevir kazı yanmasın aman kız uyanmasın.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Ayağında yok postal başına giyer püskül.',
  'Ayağında yok postal başına giyer püskül Sonradan görmesi meğersem ne müşkül.',
  'Ya hiç bir şey bilmemek pilav üstüne keşkül.',
  'Acıhda bağa vir biraz da oğa vir.',
  'Ayrana daldır yoğurduna saldır.',
  'Selam veğdi gödün mü.',
  'Selamı ağmadın mı aa.',
  'Çevir kazı yanmasın aman kız uyanmasın.',
  'Türkünün sonu geldi gari.',
  'Haydaaa.',
  'Balcının baltası var oduncunun baltası var.',
  'Öyle de olur böyle de olur.',
  'Avcı vurur turnayı biz çalarız zurnayı.',
  'Öyle de olur böyle de olur'],
 ['Adem babayla Havva anadan bu yana .',
  'Çok şeyler söylendi sevda üzerine.',
  'Sayısız türküler yapıldı Leyla ile Mecnun Ferhat ile Şirin.',
  'Hepside dertli ayrılıklarla biten ızdırap gözyaşı dolu.',
  'Hani karabasan gibi insanın dünyasını karartan sıkıntılı şeylerdi.',
  'Bugün Barış kardeşiniz sizlere yeni bir türkü söyleyecek.',
  'Çünkü Barış gördü ki yeryüzünde en büyük gerçek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Kız dediğin nazlı olur erkek ise mangal yürek.',
  'Er kişinin yanında hatun gerek.',
  'Kız dediğin nazlı olur erkek ise mangal yürek.',
  'Er kişinin yanında hatun gerek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Kız olmazsa er kişi kolsuz kanatsız demek.',
  'Davulu dengi dengine vurmak gerek.',
  'Kız olmazsa er kişi kolsuz kanatsız demek.',
  'Davulu dengi dengine vurmak gerek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Mercimek fırın yan yana fazla söze ne gerek.',
  'Deli gönül sevdi mi istemez yorgan döşek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Kimi zeytin peynir yer kimi baklava börek.',
  'Kimine saray dar gelir kimine bir oda gerek.',
  'İki göz bir kulübe yeter Havva kızına.',
  'Adem oğlu kalender yiyeceği bir lokma ekmek.',
  'Adem oğlu kızgın fırın Havva kızı mercimek.',
  'Tanrı böyle buyurmuş dünya böyle kurulmuş.',
  'Her Adem oğluna bir Havva nasip olmuş.',
  'Tanrı böyle buyurmuş dünya böyle kurulmuş.',
  'Her Adem oğluna bir Havva nasip olmuş.',
  'Yedi iklim dört kuşak inanmazsan gitte bak.',
  "Nuh'un gemisinde bile fırın mercimek dolmuş.",
  'Adem oğlu kızgın fırın Havva kızı mercimek'],
 ['Beni bırakıp gittiğinden beri.',
  'Terkedilmiş bir çocuk gibi.',
  'Çaresizim dolaştım gecelerde.',
  'Sana döndüm yine biliyorum suç bende.',
  'Affet beni ne olur affet beni.',
  'Yalvarırım soru sorma.',
  'Verilecek cevabım yok suç bende.',
  'Affet affet beni.',
  'Kendi evimde bir yabancı gibi.',
  'Çıktım ağır ağır merdivenleri.',
  'Kapıyı çalmaya cesaretim yok.',
  'Sana döndüm yine biliyorum suç bende Affet beni ne olur affet beni.',
  'Yalvarırım soru sorma.',
  'Verilecek cevabım yok suç bende.',
  'Affet affet beni.',
  'Son bir kez seni görmek istedim.',
  'Geceler boyu bu anı bekledim.',
  'Sana dönmemi istemiyorsan söyle.',
  'Söyle gideyim ama önce yine de.',
  'Affet beni ne olur affet beni.',
  'Yalvarırım soru sorma.',
  'Verilecek cevabım yok suç bende.',
  'Affet affet beni'],
 ['Ah tut-i mucize guyem, ne desem laf değil x2.',
  'Beli yarim beli dost.',
  'Beli mirim beli dost.',
  'Beli ömrüm beli dost.',
  'Ah çerh ile söyleşemem ayinesi saf değil x2.',
  'Beli yarim beli dost.',
  'Beli mirim beli dost.',
  'Beli ömrüm beli dost.',
  'Ah ehl-i dildir diyemem sinesi saf olmayana x2.',
  'Beli yarim beli dost.',
  'Beli mirim beli dost.',
  'Beli ömrüm beli dost']]

In [69]:
for element in sentence_ex_list:
    output = sa(element)

In [70]:
output

[{'label': 'positive', 'score': 0.940930187702179},
 {'label': 'positive', 'score': 0.7252164483070374},
 {'label': 'positive', 'score': 0.8965917825698853},
 {'label': 'positive', 'score': 0.9412845373153687},
 {'label': 'negative', 'score': 0.8342257738113403},
 {'label': 'positive', 'score': 0.7252164483070374},
 {'label': 'positive', 'score': 0.8965917825698853},
 {'label': 'positive', 'score': 0.9412845373153687},
 {'label': 'negative', 'score': 0.6042138934135437},
 {'label': 'positive', 'score': 0.7252164483070374},
 {'label': 'positive', 'score': 0.8965917825698853},
 {'label': 'positive', 'score': 0.8069579005241394}]

In [80]:
sentiment_ex_sentence = df_new["sentences"].apply(analyze_sentiment).tolist()

In [81]:
sentiment_ex_sentence

[None, None, None, None, None]

In [ ]:
lyric_score = []
for lyric in range(len(sentence_ex_list)):
    for 
        score = sa(list_no_stop[söz], truncation=True)
        lyric_score.append(score)

In [95]:
def sa2(inp):
    p=sa(inp)
    if p[0]['label']=='positive':
        print("{}".format(p[0]['score']))
    else:
        print("{}".format(p[0]['score']*-1))

In [96]:
def analyze_sentiment(lyrics_sentence):
    sentiments = []
    
    for sentence in lyrics_sentence:
        sentiment = sa2(sentence)
        
        sentiments.append(sentiment)
        
    return

In [104]:
sentiment_ex2_sentence = df_new["sentences"].apply(analyze_sentiment)

0.9466424584388733
-0.9877798557281494
-0.9874483942985535
0.6185345649719238
-0.9986636638641357
0.5715575218200684
-0.9710499048233032
-0.9072011709213257
-0.9904611706733704
-0.9968480467796326
0.9926995635032654
-0.9913029670715332
-0.9710499048233032
-0.9072011709213257
-0.9904611706733704
-0.9960532188415527
0.7557159662246704
-0.9128317832946777
0.8515557646751404
-0.7892162799835205
-0.9864230751991272
-0.7892162799835205
-0.6798226237297058
-0.6798226237297058
-0.9607697129249573
-0.7620126008987427
-0.7892162799835205
-0.9864230751991272
-0.7892162799835205
0.5330947041511536
-0.9359536170959473
-0.9980940222740173
-0.7892162799835205
-0.9973379969596863
0.7127324342727661
0.9099536538124084
-0.9864230751991272
-0.9275646209716797
0.9441260099411011
0.7603162527084351
0.9684363007545471
0.9692279696464539
0.9858533143997192
0.892859697341919
0.940845251083374
0.956951916217804
-0.9936961531639099
-0.9953783750534058
0.5632988214492798
0.9966161847114563
-0.9917980432510376
0.6251168847084045
-0.9330959320068359
0.6251168847084045
-0.9330959320068359
-0.9917980432510376
-0.5411453247070312
0.6938973665237427
-0.5411453247070312
0.6938973665237427
-0.9917703866958618
-0.9794872403144836
-0.9737223386764526
-0.9917980432510376
-0.9089980721473694
-0.9935228824615479
0.9534904956817627
-0.9753554463386536
-0.9917980432510376
0.9697486758232117
0.9166052341461182
0.9697486758232117
0.9166052341461182
0.980975866317749
-0.9974919557571411
-0.9804221987724304
-0.7248795628547668
-0.9967321157455444
-0.9885746836662292
0.9526678323745728
-0.9470802545547485
0.9027873277664185
-0.7640281319618225
-0.996253490447998
-0.9883842468261719
-0.5522742867469788
-0.988355278968811
0.923247754573822
0.9027873277664185
-0.7640281319618225
-0.996253490447998
0.9435995817184448
0.9751797318458557
-0.7520503997802734
-0.8229626417160034
-0.9470802545547485
0.9027873277664185
-0.7640281319618225
-0.994961142539978
0.940930187702179
0.7252164483070374
0.8965917825698853
0.9412845373153687
-0.8342257738113403
0.7252164483070374
0.8965917825698853
0.9412845373153687
-0.6042138934135437
0.7252164483070374
0.8965917825698853
0.8069579005241394

In [101]:
df_new["sentences"][0]

['Denizlerde okyanuslarda.',
 'Dalgaların koynunda bir ömür tükettikten sonra.',
 'Su için boğulmak varsa.',
 'Çöllerde kızgın kumlarda karlı buzlu dağlarda.',
 'Bir ömür tükettikten sonra.',
 'Çukurda kaybolmak varsa.',
 'Korkunun ecele faydası yok.',
 'Bu koşuşma niye.',
 'Abbas yolcu soran yok.',
 'Yolculuk nereye kim kaldı geriye Taş üstüne taş koya koya.',
 'Yarattığımız dünyanın.',
 'Çöktüğünü görmek bir yana bir de altında kalmak var ya.',
 'Korkunun ecele faydası yok.',
 'Bu koşuşma niye.',
 'Abbas yolcu soran yok.',
 'Yolculuk nereye kim kaldı geriye.',
 'Sana uzatılan elleri.',
 'Görmek istemesen de.',
 'Bir gün o eller üstünde bu dünyadan göçmek var ya']

In [115]:
analyze_sentiment(sentence_ex_list)

0.9466424584388733
-0.7892162799835205
0.892859697341919
-0.7248795628547668
0.940930187702179