In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("lyrics_class_vectors.csv")

In [3]:
df

,singer,lyrics,class,vectors
0,Barış Manço,"Denizlerde okyanuslarda, Dalgaların koynunda b...",0,"[0.10621380805969238, 0.14258037507534027, 0.2..."
1,Barış Manço,"Acıhda bağa vir biraz da oğa vir, Çevir kazı y...",3,"[-0.25285765528678894, -0.6751271486282349, -0..."
2,Barış Manço,"Adem babayla Havva anadan bu yana , Çok şeyler...",2,"[-0.2979329526424408, -0.6417730450630188, -0...."
3,Barış Manço,"Beni bırakıp gittiğinden beri, Terkedilmiş bir...",1,"[0.7641690969467163, -0.030481284484267235, 0...."
4,Barış Manço,"Ah tut-i mucize guyem, ne desem laf değil , Be...",2,"[-0.15958572924137115, 0.8297526836395264, 0.0..."
...,...,...,...,...
4423,Şebnem Ferah,"Aynıydı gökyüzümüz, Savrulduk her birimiz, İns...",0,"[-0.4530903995037079, -0.2660622298717499, -0...."
4424,Şebnem Ferah,"Alnımdan akan ter, Sana hiç değmedi, Gözümden ...",1,"[0.02522008866071701, 0.4263153374195099, 0.06..."
4425,Şebnem Ferah,"Hangi gün hangi an üzülsem ağlasam, Halime gül...",1,"[0.17655323445796967, -0.32086122035980225, -0..."
4426,Şebnem Ferah,"Biriyle fena halde konuşmaya ihtiyacım var , B...",0,"[-0.21136295795440674, 0.5752571821212769, -0...."
4427,Şebnem Ferah,"Ömür kapkaranlık, Nasıl aydınlanır, Ben yanmaz...",1,"[0.4779339134693146, -0.24386243522167206, 0.4..."

In [4]:
df["class"].dtypes

dtype('int64')

In [5]:
df_new = df[["singer", "class"]]

In [6]:
df_new

            singer  class
0      Barış Manço      0
1      Barış Manço      3
2      Barış Manço      2
3      Barış Manço      1
4      Barış Manço      2
...            ...    ...
4423  Şebnem Ferah      0
4424  Şebnem Ferah      1
4425  Şebnem Ferah      1
4426  Şebnem Ferah      0
4427  Şebnem Ferah      1

[4428 rows x 2 columns]

### Mean ile sınıflandırma

In [7]:
df_class = df_new.groupby(['singer']).mean()

In [8]:
df_class

                            class
singer
Barış Manço              1.924242
Büyük Ev Ablukada        1.478261
Can Bonomo               1.633333
Candan Erçetin           1.540146
Cem Adrian               0.742857
Cem Karaca               2.088235
Ceza                     2.565217
Duman                    1.714286
Ezhel                    2.782609
Feridun Düzağaç          0.616822
Kayahan                  1.072581
Mabel Matiz              1.444444
Mazhar Fuat Özkan (MFÖ)  1.333333
Mor Ve Ötesi             1.164948
Mustafa Sandal           1.183333
Müslüm Gürses            1.336427
Nazan Öncel              1.333333
Orhan Gencebay           1.400000
Pinhani                  0.750000
Sagopa Kajmer            2.207746
Serdar Ortaç             1.291667
Sertab Erener            1.538462
Sezen Aksu               1.271709
Tarkan                   1.338710
Teoman                   0.611765
Yaşar                    1.047170
Yeni Türkü               0.978723
Zeki Müren               1.446809
Zülfü Livaneli           1.756757
Şebnem Ferah             0.731959

### Mode ile sınıflandırma

In [9]:
#df_class_mode = df_new["class"].groupby(df_new['singer']).apply(lambda g: g.mode()).reset_index()[["singer", "class"]]
#buyuk ev ablukada ve mabel tekrar ediyor?

In [11]:
#df_class_mode

In [12]:
df_class_new = df_new.groupby('singer').agg({'class': lambda x: x.value_counts().index[0]}).reset_index()

In [13]:
df_class_new

                     singer  class
0               Barış Manço      3
1         Büyük Ev Ablukada      3
2                Can Bonomo      3
3            Candan Erçetin      1
4                Cem Adrian      0
5                Cem Karaca      3
6                      Ceza      3
7                     Duman      1
8                     Ezhel      3
9           Feridun Düzağaç      0
10                  Kayahan      2
11              Mabel Matiz      0
12  Mazhar Fuat Özkan (MFÖ)      1
13             Mor Ve Ötesi      0
14           Mustafa Sandal      1
15            Müslüm Gürses      1
16              Nazan Öncel      1
17           Orhan Gencebay      1
18                  Pinhani      0
19            Sagopa Kajmer      3
20             Serdar Ortaç      1
21            Sertab Erener      2
22               Sezen Aksu      0
23                   Tarkan      1
24                   Teoman      0
25                    Yaşar      1
26               Yeni Türkü      0
27               Zeki Müren      2
28           Zülfü Livaneli      3
29             Şebnem Ferah      0

In [14]:
sss = df_class_new.sort_values('class')

In [15]:
sss

                     singer  class
29             Şebnem Ferah      0
26               Yeni Türkü      0
24                   Teoman      0
4                Cem Adrian      0
22               Sezen Aksu      0
18                  Pinhani      0
9           Feridun Düzağaç      0
11              Mabel Matiz      0
13             Mor Ve Ötesi      0
25                    Yaşar      1
23                   Tarkan      1
20             Serdar Ortaç      1
17           Orhan Gencebay      1
16              Nazan Öncel      1
15            Müslüm Gürses      1
14           Mustafa Sandal      1
12  Mazhar Fuat Özkan (MFÖ)      1
7                     Duman      1
3            Candan Erçetin      1
10                  Kayahan      2
21            Sertab Erener      2
27               Zeki Müren      2
8                     Ezhel      3
19            Sagopa Kajmer      3
6                      Ceza      3
5                Cem Karaca      3
2                Can Bonomo      3
1         Büyük Ev Ablukada      3
28           Zülfü Livaneli      3
0               Barış Manço      3